export const TYPE_BLOOD = ['O-', 'O+', 'A-', 'A+', 'B-', 'B+', 'AB-', 'AB+','Se desconoce'];
export const COUNTRIES = [
    { code: "101", country: "NAMIBIANA", key: "NAM" },
    { code: "103", country: "ANGOLESA", key: "AGO" },
    { code: "104", country: "ARGELIANA", key: "DZA" },
    { code: "105", country: "DE BENNIN", key: "BEN" },
    { code: "106", country: "BOTSWANESA", key: "BWA" },
    { code: "107", country: "BURUNDESA", key: "BDI" },
    { code: "108", country: "DE CABO VERDE", key: "CPV" },
    { code: "109", country: "COMORENSE", key: "COM" },
    { code: "110", country: "CONGOLESA", key: "COD" },
    { code: "111", country: "MARFILE�A", key: "COG" }
    ,
    { code: "112", country: "CHADIANA", key: "TCD" },
    { code: "113", country: "DE DJIBOUTI", key: "DJI" },
    { code: "114", country: "EGIPCIA", key: "EGY" },
    { code: "115", country: "ETIOPE", key: "ETH" },
    { code: "116", country: "GABONESA", key: "GAB" },
    { code: "117", country: "GAMBIANA", key: "GMB" },
    { code: "118", country: "GHANATA", key: "GHA" },
    { code: "119", country: "GUINEA", key: "GNB" },
    { code: "120", country: "GUINEA", key: "GIN" },
    { code: "121", country: "GUINEA ECUATORIANA", key: "GNQ" },
    { code: "122", country: "LIBIA", key: "LBY" },
    { code: "123", country: "KENIANA", key: "KEN" },
    { code: "124", country: "LESOTHENSE", key: "LSO" },
    { code: "125", country: "LIBERIANA", key: "LBR" },
    { code: "127", country: "MALAWIANA", key: "MWI" },
    { code: "128", country: "MALIENSE", key: "MLI" },
    { code: "129", country: "MARROQUI", key: "MAR" },
    { code: "130", country: "MAURICIANA", key: "MUS" },
    { code: "131", country: "MAURITANA", key: "MRT" },
    { code: "132", country: "MOZAMBIQUE�A", key: "MOZ" }
    ,
    { code: "133", country: "NIGERINA", key: "NER" },
    { code: "134", country: "NIGERIANA", key: "NGA" },
    { code: "135", country: "CENTRO AFRICANA", key: "CAF" },
    { code: "136", country: "CAMERUNESA", key: "CMR" },
    { code: "137", country: "TANZANIANA", key: "TZA" },
    { code: "139", country: "RWANDESA", key: "RWA" },
    { code: "140", country: "DEL SAHARA", key: "ESH" },
    { code: "141", country: "DE SANTO TOME", key: "STP" },
    { code: "142", country: "SENEGALESA", key: "SEN" },
    { code: "143", country: "DE SEYCHELLES", key: "SYC" },
    { code: "144", country: "SIERRA LEONESA", key: "SLE" },
    { code: "145", country: "SOMALI", key: "SOM" },
    { code: "146", country: "SUDAFRICANA", key: "ZAF" },
    { code: "147", country: "SUDANESA", key: "SDN" },
    { code: "148", country: "SWAZI", key: "SWZ" },
    { code: "149", country: "TOGOLESA", key: "TGO" },
    { code: "150", country: "TUNECINA", key: "TUN" },
    { code: "151", country: "UGANDESA", key: "UGA" },
    { code: "152", country: "ZAIRANA", key: "ZAR" },
    { code: "153", country: "ZAMBIANA", key: "ZMB" },
    { code: "154", country: "DE ZIMBAWI", key: "ZWE" },
    { code: "201", country: "ARGENTINA", key: "ARG" },
    { code: "202", country: "BAHAME�A", key: "BHS" }
    ,
    { code: "203", country: "DE BARBADOS", key: "BRB" },
    { code: "204", country: "BELICE�A", key: "BLZ" }
    ,
    { code: "205", country: "BOLIVIANA", key: "BOL" },
    { code: "206", country: "BRASILE�A", key: "BRA" }
    ,
    { code: "207", country: "CANADIENSE", key: "CAN" },
    { code: "208", country: "COLOMBIANA", key: "COL" },
    { code: "209", country: "COSTARRICENSE", key: "CRI" },
    { code: "210", country: "CUBANA", key: "CUB" },
    { code: "211", country: "CHILENA", key: "CHL" },
    { code: "212", country: "DOMINICA", key: "DMA" },
    { code: "214", country: "SALVADORE�A", key: "SLV" }
    ,
    { code: "215", country: "ESTADOUNIDENSE", key: "USA" },
    { code: "216", country: "GRANADINA", key: "VCT" },
    { code: "217", country: "GUATEMALTECA", key: "GTM" },
    { code: "218", country: "BRITANICA", key: "VGB" },
    { code: "219", country: "GUYANESA", key: "GUY" },
    { code: "220", country: "HAITIANA", key: "HTI" },
    { code: "221", country: "HONDURE�A", key: "HND" }
    ,
    { code: "222", country: "JAMAIQUINA", key: "JAM" },
    { code: "223", country: "MEXICANA", key: "MEX" },
    { code: "224", country: "NICARAGUENSE", key: "NIC" },
    { code: "225", country: "PANAME�A", key: "PAN" }
    ,
    { code: "226", country: "PARAGUAYA", key: "PRY" },
    { code: "227", country: "PERUANA", key: "PER" },
    { code: "228", country: "PUERTORRIQUE�A", key: "PRI" }
    ,
    { code: "229", country: "DOMINICANA", key: "DOM" },
    { code: "230", country: "SANTA LUCIENSE", key: "LCA" },
    { code: "231", country: "SURINAMENSE", key: "SUR" },
    { code: "232", country: "TRINITARIA", key: "TTO" },
    { code: "233", country: "URUGUAYA", key: "URY" },
    { code: "234", country: "VENEZOLANA", key: "VEN" },
    { code: "299", country: "AMERICANA", key: "USA" },
    { code: "301", country: "AFGANA", key: "AFG" },
    { code: "303", country: "DE BAHREIN", key: "BHR" },
    { code: "305", country: "BHUTANESA", key: "BTN" },
    { code: "306", country: "BIRMANA", key: "BUR" },
    { code: "307", country: "NORCOREANA", key: "PRK" },
    { code: "308", country: "SUDCOREANA", key: "KOR" },
    { code: "309", country: "CHINA", key: "CHN" },
    { code: "310", country: "CHIPRIOTA", key: "CYP" },
    { code: "311", country: "ARABE", key: "SAU" },
    { code: "312", country: "FILIPINA", key: "PHL" },
    { code: "313", country: "HINDU", key: "IND" },
    { code: "314", country: "INDONESA", key: "IDN" },
    { code: "315", country: "IRAQUI", key: "IRQ" },
    { code: "316", country: "IRANI", key: "IRN" },
    { code: "317", country: "ISRAELI", key: "ISR" },
    { code: "318", country: "JAPONESA", key: "JPN" },
    { code: "319", country: "JORDANA", key: "JOR" },
    { code: "320", country: "CAMBOYANA", key: "KHM" },
    { code: "321", country: "KUWAITI", key: "KWT" },
    { code: "322", country: "LIBANESA", key: "LBN" },
    { code: "323", country: "MALASIA", key: "MYS" },
    { code: "324", country: "MALDIVA", key: "MDV" },
    { code: "325", country: "MONGOLESA", key: "MNG" },
    { code: "326", country: "NEPALESA", key: "NPL" },
    { code: "327", country: "OMANESA", key: "OMN" },
    { code: "328", country: "PAKISTANI", key: "PAK" },
    { code: "329", country: "DEL QATAR", key: "QAT" },
    { code: "330", country: "SIRIA", key: "SYR" },
    { code: "331", country: "LAOSIANA", key: "LAO" },
    { code: "332", country: "SINGAPORENSE", key: "SGP" },
    { code: "334", country: "TAILANDESA", key: "THA" },
    { code: "335", country: "TAIWANESA", key: "TWN" },
    { code: "336", country: "TURCA", key: "TUR" },
    { code: "337", country: "NORVIETNAMITA", key: "VNM" },
    { code: "339", country: "YEMENI", key: "YEM" },
    { code: "401", country: "ALBANESA", key: "ALB" },
    { code: "403", country: "ALEMANA", key: "DEU" },
    { code: "404", country: "ANDORRANA", key: "AND" },
    { code: "405", country: "AUSTRIACA", key: "AUT" },
    { code: "406", country: "BELGA", key: "BEL" },
    { code: "407", country: "BULGARA", key: "BGR" },
    { code: "408", country: "CHECOSLOVACA", key: "CSK" },
    { code: "409", country: "DANESA", key: "DNK" },
    { code: "410", country: "VATICANA", key: "VAT" },
    { code: "411", country: "ESPA�OLA", key: "ESP" }
    ,
    { code: "412", country: "FINLANDESA", key: "FIN" },
    { code: "413", country: "FRANCESA", key: "FRA" },
    { code: "414", country: "GRIEGA", key: "GRC" },
    { code: "415", country: "HUNGARA", key: "HUN" },
    { code: "416", country: "IRLANDESA", key: "IRL" },
    { code: "417", country: "ISLANDESA", key: "ISL" },
    { code: "418", country: "ITALIANA", key: "ITA" },
    { code: "419", country: "LIECHTENSTENSE", key: "LIE" },
    { code: "420", country: "LUXEMBURGUESA", key: "LUX" },
    { code: "421", country: "MALTESA", key: "MLT" },
    { code: "422", country: "MONEGASCA", key: "MCO" },
    { code: "423", country: "NORUEGA", key: "NOR" },
    { code: "424", country: "HOLANDESA", key: "NLD" },
    { code: "426", country: "PORTUGUESA", key: "PRT" },
    { code: "427", country: "BRITANICA", key: "IOT" },
    { code: "428", country: "SOVIETICA BIELORRUSA", key: "BLR" },
    { code: "429", country: "SOVIETICA UCRANIANA", key: "UKR" },
    { code: "430", country: "RUMANA", key: "ROM" },
    { code: "431", country: "SAN MARINENSE", key: "SMR" },
    { code: "432", country: "SUECA", key: "SWE" },
    { code: "433", country: "SUIZA", key: "CHE" },
    { code: "435", country: "YUGOSLAVA", key: "YUG" },
    { code: "501", country: "AUSTRALIANA", key: "AUS" },
    { code: "502", country: "FIJIANA", key: "FJI" },
    { code: "503", country: "SALOMONESA", key: "SLB" },
    { code: "504", country: "NAURUANA", key: "NRU" },
    { code: "506", country: "PAPUENSE", key: "PNG" },
    { code: "507", country: "SAMOANA", key: "WSM" },
    { code: "667", country: "ESLOVACA", key: "SVK" },
    { code: "609", country: "BURKINA FASO", key: "BFA" },
    { code: "621", country: "ESTONIA", key: "EST" },
    { code: "624", country: "MICRONECIA", key: "FSM" },
    { code: "625", country: "REINO UNIDO(DEPEN. TET. BRIT.)", key: "GBD" },
    { code: "626", country: "REINO UNIDO(BRIT. DEL EXT.)", key: "GBN" },
    { code: "627", country: "REINO UNIDO(C. BRIT. DEL EXT.)", key: "GBO" },
    { code: "629", country: "REINO UNIDO", key: "GBR" },
    { code: "642", country: "KIRGUISTAN", key: "KGZ" },
    { code: "645", country: "LITUANIA", key: "LTU" },
    { code: "648", country: "MOLDOVIA, REPUBLICA DE", key: "MDA" },
    { code: "650", country: "MACEDONIA", key: "MKD" },
    { code: "668", country: "ESLOVENIA", key: "SVN" },
    { code: "684", country: "ESLOVAQUIA", key: "XES" }
];
export const ESTATES = [{ clave: "1", estado: "Aguascalientes", abreviatura: "Ags." }, { clave: "10", estado: "Durango", abreviatura: "Dgo." }, { clave: "11", estado: "Guanajuato", abreviatura: "Gto." }, { clave: "12", estado: "Guerrero", abreviatura: "Gro." }, { clave: "13", estado: "Hidalgo", abreviatura: "Hgo." }, { clave: "14", estado: "Jalisco", abreviatura: "Jal." }, { clave: "15", estado: "M\u00c3\u00a9xico", abreviatura: "Mex." }, { clave: "16", estado: "Michoac", abreviatura: "Mich." }, { clave: "17", estado: "Morelos", abreviatura: "Mor." }, { clave: "18", estado: "Nayarit", abreviatura: "Nay." }, { clave: "19", estado: "Nuevo Leon", abreviatura: "NL" }, { clave: "2", estado: "Baja California", abreviatura: "BC" }, { clave: "20", estado: "Oaxaca", abreviatura: "Oax." }, { clave: "21", estado: "Puebla", abreviatura: "Pue." }, { clave: "22", estado: "Quer", abreviatura: "Qro." }, { clave: "23", estado: "Quintana Roo", abreviatura: "Q. Roo" }, { clave: "24", estado: "San Luis Potosi", abreviatura: "SLP" }, { clave: "25", estado: "Sinaloa", abreviatura: "Sin." }, { clave: "26", estado: "Sonora", abreviatura: "Son." }, { clave: "27", estado: "Tabasco", abreviatura: "Tab." }, { clave: "28", estado: "Tamaulipas", abreviatura: "Tamps." }, { clave: "29", estado: "Tlaxcala", abreviatura: "Tlax." }, { clave: "3", estado: "Baja California Sur", abreviatura: "BCS" }, { clave: "30", estado: "Veracruz de Ignacio de la Llave", abreviatura: "Ver." }, { clave: "31", estado: "Yucatan", abreviatura: "Yuc." }, { clave: "32", estado: "Zacatecas", abreviatura: "Zac." }, { clave: "4", estado: "Campeche", abreviatura: "Camp." }, { clave: "5", estado: "Coahuila de Zaragoza", abreviatura: "Coah." }, { clave: "6", estado: "Colima", abreviatura: "Col." }, { clave: "7", estado: "Chiapas", abreviatura: "Chis." }, { clave: "8", estado: "Chihuahua", abreviatura: "Chih." }, { clave: "9", estado: "Ciudad de M", abreviatura: "CDMX" }];
export const TYPES = [
    {clave: 'A', tipo: 'Automovilista'},
    {clave: 'C', tipo: 'Chofer'},
    {clave: 'M', tipo: 'Motociclista'},
    {clave: 'P', tipo: 'Permiso de menor'}
];
export const VALIDTY = ['3 años','5 años'];
export const FORMATS = ['Municipal', 'Estatal'];
export const DEFAULT_LANGUAGE = 'es';
export const ADMINITEMS = [
    {route: 'usuarios', icon: 'ic-users', label: 'Usuarios'},
    {route: 'licencias', icon: 'ic-licenses', label: 'Licencias'}
]
export const MASTER_OPTIONS = [
    {label: 'Usuarios'},
    {label: 'Folios'}
];

export const PRESIDENT_OPTIONS = [
    {icon: 'ic-users', label: 'Usarios'},
    {icon: 'ic-folio', label: 'Folios'}
];

export const MASTER_COLUMNS = ['uid', 'correo', 'nombre','rol','dots'];
export const CUENTAS = ['Común','Administrador'];
export const CURP_REGEX = /^([A-Z][AEIOUX][A-Z]{2}\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z\d])(\d)$/;
export const VIN_REGEX = /[a-zA-Z0-9]{9}$/;
export const YEAR_REGEX = /[0-9]{4}$/;
export const INVOICE_REGEX = /[0-9]$/;
export const FUNDAMENT = 'Con fundamento en lo dispuesto por los artículos 115 fracciones II y III, incisos h) e i) de la Constitución Política de los Estados Unidos Mexicanos; 20 fracción XXXI de la Ley Orgánica de la Administración Pública del Estado de Guerrero; 28 de la Ley de Transporte y Vialidad del Estado de Guerrero; 1° de la Ley de Ingresos del Estado de Guerrero, para el ejercicio fiscal 2014; 104 fracción VIII inciso b) párrafo segundo de la Ley de Hacienda del Estado de Guerrero número 428, y conforme al Anexo 2 del Convenio de Colaboración Administrativa en Materia Fiscal para la delegación de facultades de verificación del cumplimiento de obligaciones fiscales, con relación a los pagos del impuesto sobre tenencia o uso de vehículos y de los derechospor la expedición de placas, tarjeta de circulación y calcomanía de matrícula, de fecha 31 de octubre de 2012.';
export const VALIDATE = 'Para comprobar validez de la licencia, verifíquela en la siguiente dirección de internet: www.transitomunicipalcuautepecgro.gob.mx';
export const PORTAL = 'Véase en el portal de gobierno del estado, en Consejería Jurídica.';
export const SNACK_BAR = {
    logoUpdated: "Logos actualizados",
    dataSavedSuccessfully: 'Tus datos se han guardado exitosamente',
    emailSent: 'Se envió un correo para recuperar tu contraseña.',
    youDoNotHaveAuthorization: 'Tu cuenta no es de tipo administrador.',
    establishmentCreated: 'Nuevo establecimiento creado',
    establishmentUpdated: 'El establecimiento ha sido actualizado',
    disableStore: 'El establecimiento ha sido desactivado',
    activeStore: 'El establecimiento ha sido activado',
    notificationCreated: 'Nueva notificación creada',
    notificationUpdated: 'La notificación ha sido actualizada',
    deleteNotification: 'La notificación ha sido eliminada',
    awardCreated: 'Nuevo premio creado',
    awardUpdated: 'El premio ha sido actualizado',
    deleteAward: 'El premio ha sido eliminado',
    advertisingCreated: 'Nueva publicidad creada',
    advertisingUpdated: 'La publicidad ha sido actualizada',
    deleteAdvertising: 'La publicidad ha sido eliminada',
    promotionCreated: 'Nueva promoción creada',
    promotionUpdated: 'La promoción ha sido actualizada',
    deletePromotion: 'La promoción ha sido eliminada',
    notAllowedFormat: 'Formato de archivo invalido',
    notAllowedSize: 'Tamaño de imagen excedido',
    bannerUpdated: 'Banners actualizados',
    couponDelete: 'El cupón ha sido eliminado',
    couponCreated: 'Nuevo cupón creado',
    couponUpdated: 'Cambios guardados correctamente',
    couponRepeated: 'Ya existe un cupón con este nombre',
    couponCodeRepeated: 'Ya existe un cupón con este código',
    notStructure: 'La estructura del archivo de excel es invalida',
    notNumberAllowed: 'No se admiten números menores a cero'
};